-- History marker for the production migration 20260728174335_disable_http_after_meta_roles_audit.
-- The original migration performed a one-time external diagnostic/audit and is intentionally
-- not replayed during deterministic database rebuilds. It made no persistent product-schema change.
