-- History marker for the production migration 20260728173402_enable_http_for_meta_diagnostic.
-- The original migration performed a one-time external diagnostic/audit and is intentionally
-- not replayed during deterministic database rebuilds. It made no persistent product-schema change.
