-- History marker for the production migration 20260728221223_disable_pg_net_after_ai_generator_v2_audit.
-- The original migration performed a one-time external diagnostic/audit and is intentionally
-- not replayed during deterministic database rebuilds. It made no persistent product-schema change.
