-- History marker for the production migration 20260728220057_enable_pg_net_for_agent_generator_audit.
-- The original migration performed a one-time external diagnostic/audit and is intentionally
-- not replayed during deterministic database rebuilds. It made no persistent product-schema change.
