-- History marker for the production migration 20260728201737_enable_pg_net_for_meta_number_audit.
-- The original migration performed a one-time external diagnostic/audit and is intentionally
-- not replayed during deterministic database rebuilds. It made no persistent product-schema change.
