-- History marker for the production migration 20260728221145_assert_agent_generator_v2_passed.
-- The original migration performed a one-time external diagnostic/audit and is intentionally
-- not replayed during deterministic database rebuilds. It made no persistent product-schema change.
